### PR TITLE
fix: search bar on right side

### PR DESCRIPTION
**Pull request by racky7**

### CODE REVIEW

**Comment by danishzayan** [comment]
@racky7 on ON dark mode button break when click search bar fix this after that i will merge yourc ode...

**Comment by racky7** [comment]
@danishzayan Have a look now.

**Comment by danishzayan** [comment]
> @danishzayan Have a look now.

Great but in responsive transition witdh should be 100% see previous in responsive

**Comment by racky7** [comment]
@danishzayan is it okay now?

**Review by danishzayan — APPROVED** [review]

**Comment by danishzayan** [comment]
@racky7 gud job and keep contributing..😊

**Pull request merged**
