### PR TITLE
Move search bar to header

### PR DESCRIPTION
**Pull request by Neesh774**

### CODE REVIEW

**Comment by danishzayan** [comment]
@Neesh774 move search bar in header not looking good so please improve and give a awesome design to search 🔎 so that looks good

**Comment by Neesh774** [comment]
@danishzayan I made it look better

**Comment by danishzayan** [comment]
@Neesh774 good work i like your work but plz fixed search bar for mobile responsive...

**Comment by danishzayan** [comment]
> @danishzayan I made it look better

@Neesh774 you have done good.. plz do responsive for mobile and tablet after that i will merge..

**Comment by Neesh774** [comment]
fixed responsivity @danishzayan

**Review by danishzayan — APPROVED** [review]

**Comment by danishzayan** [comment]
@Neesh774 there are some conflicts after resolve i will merge your code.. you have done gud work 💗

**Review by danishzayan — APPROVED** [review]

**Comment by danishzayan** [comment]
@Neesh774 create a branch after that push your code bcz conflicts is not solving in github

**Comment by danishzayan** [comment]
@Neesh774 plz create new branch then push your code bcz conflicts is not resolving after that I will merge you code...

**Pull request closed without merging**
