### PR TITLE
Added title for icons and shows search result amount

### PR DESCRIPTION
**Pull request by Saran-pariyar**
Changes:
1. Made title text appear when we hover on icons and in add note button.
Screenshot from 2022-10-03 22-00-43

2. It will show the resulting amount when we search for something and hides the section if we didn't search anything.
Screenshot from 2022-10-03 22-17-02

### CODE REVIEW

**Comment by danishzayan** [comment]
@Saran-pariyar there are some conflicts .. resolve your code after that create a pr..

**Comment by danishzayan** [comment]
@Saran-pariyar then i wil merge your code

**Comment by Saran-pariyar** [comment]
Just solved the conflict and making a new pull request, please check

**Review by danishzayan — APPROVED** [review]

**Comment by danishzayan** [comment]
@Saran-pariyar Gud job and keep contributing ...  don't forget give a star ⭐ to repo...

**Pull request merged**
