### PR TITLE
fix: show latest quote first (issue #29)

### PR DESCRIPTION
**Pull request by VectorXz**
fix: show latest quote first (issue #29)

### CODE REVIEW

**Review by danishzayan — APPROVED** [review]

**Comment by danishzayan** [comment]
@VectorXz quotes is showing first but when refresh the page that quotes is not showing plz fix this hurry up...

**Comment by VectorXz** [comment]
@danishzayan 
As I observed, the quotes still shown after refresh.
BUT, if you're adding new quote and refresh it will not show up due to the limit of API.
I think you are running out of resources on API
image

**Comment by danishzayan** [comment]
> @danishzayan As I observed, the quotes still shown after refresh. BUT, if you're adding new quote and refresh it will not show up due to the limit of API. I think you are running out of resources on API image

Ok i see

**Comment by danishzayan** [comment]
@VectorXz Have you knowledge of Strapi CMS...

**Comment by VectorXz** [comment]
No... sorry.

**Comment by danishzayan** [comment]
[Strapi](https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html#_1-install-strapi-and-create-a-new-project)

**Comment by danishzayan** [comment]
@VectorXz ok all is well.. gud job 🤩

**Pull request merged**
