### PR TITLE
share card changes

### PR DESCRIPTION
**Pull request by Kunal-deve1oper**

### CODE REVIEW

**Comment by danishzayan** [comment]
@Kunal-deve1oper plz resolve the conflict after that once again push ur code

**Comment by danishzayan** [comment]
IMG_20221009_004016

When  I link share preview is not working...

**Comment by Kunal-deve1oper** [comment]
> IMG_20221009_004016
> 
> When I link share preview is not working...

i am looking into it

**Comment by Kunal-deve1oper** [comment]
> IMG_20221009_004016
> 
> When I link share preview is not working...

 it is working perfectly in my localhost but its not working when we are hosting it .  I used dynamic routing and I do not know why its mot working when we are hosting it

**Pull request closed without merging**
