### PR TITLE
resolve #34 - Fixed dark mode not staying after page reload

### LINKED ISSUE #34: Darkmode issue
After refresh the page dark mode should be show in dark mode 🌑 not show in light mode..

### PR DESCRIPTION
**Pull request by Irjean**

### CODE REVIEW

**Comment by danishzayan** [comment]
@Irjean but should not be off in dark mode after refresh check it...

**Comment by NalinPlad** [comment]
looks good to me

**Comment by danishzayan** [comment]
> looks good to me

@NalinPlad ok you can do it

**Comment by danishzayan** [comment]
> @danishzayan I fixed it !

@Irjean Great 😊

**Pull request merged**
