### PR TITLE
Move search bar to header and make it responsive

### PR DESCRIPTION
**Pull request by Neesh774**

### CODE REVIEW

**Comment by danishzayan** [comment]
@Neesh774 search 🔎 is not working and see screenshot 

Screenshot_2022-10-03-17-14-00-47

**Comment by Neesh774** [comment]
Fixed @danishzayan

**Comment by Neesh774** [comment]
Sorry, fixed search and fixed merge conflicts

**Review by danishzayan — APPROVED** [review]

**Comment by danishzayan** [comment]
@Neesh774 Gud work.. 😊 don't forget give to repo...

**Pull request merged**
