### PR TITLE
Feature: Add popup that lets user add a YourQuote

### PR DESCRIPTION
**Pull request by mritul**

### CODE REVIEW

**Comment by mritul** [comment]
@danishzayan  I've implemented all the requested changes and I couldn't implement a black overlay but still implemented a white toned overlay. Hope it's fine with you. It would be great if you merged the PR with the hacktoberfest-accepted tag once you're satisfied with the performed changes. Thank you ❤️

**Review by danishzayan — APPROVED** [review]
Gud work

**Comment by danishzayan** [comment]
@mritul gud work 😊 and keep contributing...

**Comment by mritul** [comment]
Thanks @danishzayan :D. Is there any other issue that you can assign to me  ? I'd be happy to work on it as well

**Pull request merged**
