### PR TITLE
I have successfully added a Scroll to top button on bottom right corner

### PR DESCRIPTION
**Pull request by Eyesnatcher-coder**
Hey @danishzayan , I have completed my work please make a merge of my PR.

### CODE REVIEW

**Comment by danishzayan** [comment]
@Eyesnatcher-coder  It goes at once top page and it is not smooth scrolling... Plz fix this after that I will merge ur code...

**Comment by Eyesnatcher-coder** [comment]
Thanks @danishzayan :)

**Comment by danishzayan** [comment]
> Thanks @danishzayan :)

Wlcm

**Comment by Eyesnatcher-coder** [comment]
@danishzayan I am extremely sorry, I didn't saw your comment, I got to know now when you merged. 
Sorry for inconvenience  :(

**Comment by danishzayan** [comment]
> @danishzayan I am extremely sorry, I didn't saw your comment, I got to know now when you merged. Sorry for inconvenience :(

It's okay.. no matter

**Pull request merged**
